version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: campeonato_mysql
    environment:
      MYSQL_ROOT_PASSWORD: campeonato
      MYSQL_DATABASE: meucampeonato
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pcampeonato"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 30s  
    networks:
      - campeonato_net
    restart: unless-stopped

  app:
    build:
      context: .
      target: production 
    container_name: campeonato_app
    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=campeonato
      - DB_DATABASE=meucampeonato
      - PORT=3000
      - NODE_ENV=production
      - DB_RETRY_ATTEMPTS=10
      - DB_RETRY_DELAY=5000
      - DB_CONNECT_TIMEOUT=30000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - campeonato_net
    restart: unless-stopped
    stdin_open: true
    tty: true
    entrypoint: ["sh", "-c", "sleep 20 && node dist/main.js"]  # Delay generoso

volumes:
  mysql_data:
    driver: local

networks:
  campeonato_net:
    driver: bridge